[IN PROGRESS] Edits to extension README
microsoft/azure-pipelines-extensions pull request #1107
Opened 2022-12-06 22:34 UTC by juliakm

2022-12-07 16:14 UTC, silviuandrica requested changes

2022-12-08 16:12 UTC, juliakm commented on ServerTaskHelper/AzureFunctionAdvancedHandler/README.md
> +This advanced example shows how to trigger an Azure Function to fire once a pipeline run ends that was kicked off by a commit with a related [Azure Boards](https://azure.microsoft.com/products/devops
I've updated this but I'm not sure it's quite right.

2022-12-08 16:13 UTC, juliakm commented on ServerTaskHelper/AzureFunctionAdvancedHandler/README.md
> +This advanced example shows how to trigger an Azure Function to fire once a pipeline run ends that was kicked off by a commit with a related [Azure Boards](https://azure.microsoft.com/products/devops
Updated to "This advanced example shows how to trigger an Azure Function that checks if an [Azure Boards](https://azure.microsoft.com/products/devops/boards/) work item is in a **Completed** state"

2022-12-08 17:20 UTC, silviuandrica approved these changes
Thank you, @juliakm!

2022-12-08 17:20 UTC, merged