Enabling Ansible task for Deployment Group and merging master to release
microsoft/azure-pipelines-extensions pull request #633
Opened 2019-06-13 08:46 UTC by vinodkumar3

2019-06-13 10:25 UTC, sachinma requested changes

2019-06-13 10:42 UTC, vinodkumar3 commented on Extensions/Ansible/Src/Tasks/Ansible/ansibleCommandLineInterface.ts
> +                let remoteInventory = ansibleUtils.getTemporaryInventoryFilePath();
Its a part of 4 months old [PR](https://github.com/microsoft/azure-pipelines-extensions/pull/592/files).
@amaljg are you fine merging your PR changes to release branch now ?

2019-06-13 11:51 UTC, sachinma commented on Extensions/Ansible/Src/Tasks/Ansible/ansibleCommandLineInterface.ts
> +                let remoteInventory = ansibleUtils.getTemporaryInventoryFilePath();
why don't you just cherry-pick your PR

2019-06-13 12:19 UTC, omeshp approved these changes

2019-06-13 17:02 UTC, amaljg approved these changes

2019-06-14 04:35 UTC, vinodkumar3 commented on Extensions/Ansible/Src/Tasks/Ansible/ansibleCommandLineInterface.ts
> +                let remoteInventory = ansibleUtils.getTemporaryInventoryFilePath();
As I said multiple merge conflicts comes into picture in azure-pipelines-extensions\package-lock.json when I just cherry-pick my changes

2019-06-14 04:54 UTC, sachinma approved these changes

2019-06-14 05:48 UTC, merged